# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e17c1f8cd98ae071d13fa0003e6d2e1"
name = "palvento"
application_url = "https://palvento.com"
embedded = false
handle = "palvento-multichannel"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/shopify/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/shopify/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_inventory,read_locations,read_orders,read_price_rules,read_products,read_publications,write_inventory,write_price_rules,write_products,write_publications"

[auth]
redirect_urls = [
  "https://palvento.com/api/shopify/callback",
  "https://auxio-lkqv.vercel.app/api/shopify/callback"
]
