/**
 * Seed mapping: Shopify product_type / tags / title keywords → eBay leaf categoryId.
 *
 * Hand-curated from eBay UK's (and US-compatible) category tree for the top ~500
 * Shopify product types across apparel, home, electronics, beauty, sports, toys,
 * jewelry, pet, books, automotive, baby, and health.
 *
 * Confidence: 0..1. Exact `shopifyType` match uses the entry's confidence as-is;
 * fuzzy keyword/tag matches multiply by an overlap ratio.
 *
 * Adding a new mapping: append a new entry. The matcher iterates this array, so
 * first-match-wins on exact `shopifyType` (lowercased). Keep the most specific
 * product types near the top when two compete for the same phrase.
 */

export interface SeedCategoryEntry {
  shopifyType: string
  shopifyTagsAll?: string[]
  shopifyTitleKeywords?: string[]
  ebayCategoryId: string
  ebayCategoryPath: string
  confidence: number
}

export const SEED_EBAY_CATEGORIES: SeedCategoryEntry[] = [
  // ── Women's apparel ──
  { shopifyType: 'dress', shopifyTitleKeywords: ['dress', 'gown'], ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.95 },
  { shopifyType: 'dresses', ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.95 },
  { shopifyType: "women's dress", ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.97 },
  { shopifyType: 'maxi dress', ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.95 },
  { shopifyType: 'mini dress', ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.95 },
  { shopifyType: 'evening dress', ebayCategoryId: '63861', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Dresses", confidence: 0.95 },
  { shopifyType: 'top', shopifyTitleKeywords: ['blouse', 'top'], ebayCategoryId: '53159', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Tops & Shirts", confidence: 0.85 },
  { shopifyType: 'blouse', ebayCategoryId: '53159', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Tops & Shirts", confidence: 0.95 },
  { shopifyType: "women's top", ebayCategoryId: '53159', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Tops & Shirts", confidence: 0.96 },
  { shopifyType: 't-shirt', shopifyTitleKeywords: ['tee', 't-shirt'], ebayCategoryId: '15687', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > T-Shirts", confidence: 0.92 },
  { shopifyType: 'tee', ebayCategoryId: '15687', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > T-Shirts", confidence: 0.9 },
  { shopifyType: "women's t-shirt", ebayCategoryId: '15687', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > T-Shirts", confidence: 0.96 },
  { shopifyType: 'skirt', ebayCategoryId: '63864', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Skirts", confidence: 0.95 },
  { shopifyType: 'mini skirt', ebayCategoryId: '63864', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Skirts", confidence: 0.95 },
  { shopifyType: 'midi skirt', ebayCategoryId: '63864', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Skirts", confidence: 0.95 },
  { shopifyType: 'jeans', ebayCategoryId: '11554', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jeans", confidence: 0.95 },
  { shopifyType: "women's jeans", ebayCategoryId: '11554', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jeans", confidence: 0.97 },
  { shopifyType: 'trousers', ebayCategoryId: '63863', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Trousers", confidence: 0.95 },
  { shopifyType: 'pants', ebayCategoryId: '63863', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Trousers", confidence: 0.9 },
  { shopifyType: 'leggings', ebayCategoryId: '169001', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Leggings", confidence: 0.95 },
  { shopifyType: 'shorts', ebayCategoryId: '11555', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Shorts", confidence: 0.9 },
  { shopifyType: 'jumpsuit', ebayCategoryId: '3009', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jumpsuits & Playsuits", confidence: 0.95 },
  { shopifyType: 'playsuit', ebayCategoryId: '3009', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jumpsuits & Playsuits", confidence: 0.95 },
  { shopifyType: 'jumper', ebayCategoryId: '63866', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jumpers & Cardigans", confidence: 0.95 },
  { shopifyType: 'cardigan', ebayCategoryId: '63866', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jumpers & Cardigans", confidence: 0.95 },
  { shopifyType: 'sweater', ebayCategoryId: '63866', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Jumpers & Cardigans", confidence: 0.92 },
  { shopifyType: 'hoodie', ebayCategoryId: '155226', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Hoodies & Sweatshirts", confidence: 0.95 },
  { shopifyType: 'sweatshirt', ebayCategoryId: '155226', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Hoodies & Sweatshirts", confidence: 0.92 },
  { shopifyType: 'coat', ebayCategoryId: '63862', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Coats, Jackets & Waistcoats", confidence: 0.95 },
  { shopifyType: 'jacket', ebayCategoryId: '63862', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Coats, Jackets & Waistcoats", confidence: 0.9 },
  { shopifyType: 'blazer', ebayCategoryId: '63862', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Coats, Jackets & Waistcoats", confidence: 0.9 },
  { shopifyType: 'lingerie', ebayCategoryId: '63853', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Lingerie & Nightwear", confidence: 0.95 },
  { shopifyType: 'nightwear', ebayCategoryId: '63853', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Lingerie & Nightwear", confidence: 0.95 },
  { shopifyType: 'pyjamas', ebayCategoryId: '63853', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Lingerie & Nightwear", confidence: 0.95 },
  { shopifyType: 'bra', ebayCategoryId: '11514', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Lingerie & Nightwear > Bras", confidence: 0.95 },
  { shopifyType: 'knickers', ebayCategoryId: '63855', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Lingerie & Nightwear > Knickers", confidence: 0.95 },
  { shopifyType: 'swimwear', ebayCategoryId: '63867', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Swimwear", confidence: 0.95 },
  { shopifyType: 'bikini', ebayCategoryId: '63867', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Swimwear", confidence: 0.95 },
  { shopifyType: 'activewear', ebayCategoryId: '137084', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Activewear", confidence: 0.95 },
  { shopifyType: 'sportswear', ebayCategoryId: '137084', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Activewear", confidence: 0.9 },
  { shopifyType: 'gym wear', ebayCategoryId: '137084', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Activewear", confidence: 0.9 },
  { shopifyType: 'yoga wear', ebayCategoryId: '137084', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Clothing > Activewear", confidence: 0.9 },

  // ── Men's apparel ──
  { shopifyType: "men's t-shirt", ebayCategoryId: '15687', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > T-Shirts", confidence: 0.97 },
  { shopifyType: "men's shirt", ebayCategoryId: '1059', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Shirts", confidence: 0.97 },
  { shopifyType: 'shirt', shopifyTitleKeywords: ['shirt', 'button-down'], ebayCategoryId: '1059', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Shirts", confidence: 0.82 },
  { shopifyType: 'polo shirt', ebayCategoryId: '1059', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Shirts", confidence: 0.9 },
  { shopifyType: "men's jeans", ebayCategoryId: '11483', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Jeans", confidence: 0.97 },
  { shopifyType: "men's trousers", ebayCategoryId: '57989', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Trousers", confidence: 0.97 },
  { shopifyType: "men's shorts", ebayCategoryId: '15689', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Shorts", confidence: 0.95 },
  { shopifyType: "men's jumper", ebayCategoryId: '11484', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Jumpers & Cardigans", confidence: 0.95 },
  { shopifyType: "men's hoodie", ebayCategoryId: '155183', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Hoodies & Sweatshirts", confidence: 0.95 },
  { shopifyType: "men's coat", ebayCategoryId: '57988', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Coats & Jackets", confidence: 0.95 },
  { shopifyType: "men's jacket", ebayCategoryId: '57988', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Coats & Jackets", confidence: 0.95 },
  { shopifyType: "men's suit", ebayCategoryId: '3001', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Suits & Tailoring", confidence: 0.95 },
  { shopifyType: 'suit', ebayCategoryId: '3001', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Suits & Tailoring", confidence: 0.85 },
  { shopifyType: "men's underwear", ebayCategoryId: '11507', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Underwear", confidence: 0.95 },
  { shopifyType: "men's swimwear", ebayCategoryId: '15690', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Swimwear", confidence: 0.95 },
  { shopifyType: "men's activewear", ebayCategoryId: '137084', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Clothing > Activewear", confidence: 0.95 },
  { shopifyType: 'tie', ebayCategoryId: '15662', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Accessories > Ties, Bow Ties & Cravats", confidence: 0.9 },

  // ── Footwear ──
  { shopifyType: 'shoes', ebayCategoryId: '3034', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes", confidence: 0.75 },
  { shopifyType: "women's shoes", ebayCategoryId: '3034', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes", confidence: 0.95 },
  { shopifyType: "men's shoes", ebayCategoryId: '93427', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Shoes", confidence: 0.95 },
  { shopifyType: 'trainers', ebayCategoryId: '15709', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Trainers", confidence: 0.9 },
  { shopifyType: 'sneakers', ebayCategoryId: '15709', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Trainers", confidence: 0.9 },
  { shopifyType: 'boots', ebayCategoryId: '53557', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Boots", confidence: 0.9 },
  { shopifyType: 'heels', ebayCategoryId: '55793', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Heels", confidence: 0.95 },
  { shopifyType: 'flats', ebayCategoryId: '45333', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Flats", confidence: 0.9 },
  { shopifyType: 'sandals', ebayCategoryId: '62107', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Sandals", confidence: 0.9 },
  { shopifyType: 'slippers', ebayCategoryId: '62225', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Slippers", confidence: 0.9 },
  { shopifyType: 'loafers', ebayCategoryId: '95672', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Shoes > Loafers", confidence: 0.9 },
  { shopifyType: 'athletic shoes', ebayCategoryId: '15709', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Trainers", confidence: 0.9 },
  { shopifyType: 'running shoes', ebayCategoryId: '15709', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Shoes > Trainers", confidence: 0.9 },

  // ── Accessories / bags / jewelry ──
  { shopifyType: 'bag', ebayCategoryId: '169291', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Bags & Handbags", confidence: 0.8 },
  { shopifyType: 'handbag', ebayCategoryId: '169291', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Bags & Handbags", confidence: 0.95 },
  { shopifyType: 'tote bag', ebayCategoryId: '169291', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Bags & Handbags", confidence: 0.95 },
  { shopifyType: 'backpack', ebayCategoryId: '169291', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Bags & Handbags", confidence: 0.9 },
  { shopifyType: 'wallet', ebayCategoryId: '169284', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Purses & Wallets", confidence: 0.9 },
  { shopifyType: 'purse', ebayCategoryId: '169284', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Purses & Wallets", confidence: 0.9 },
  { shopifyType: 'belt', ebayCategoryId: '3003', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Belts", confidence: 0.9 },
  { shopifyType: 'hat', ebayCategoryId: '45230', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Hats", confidence: 0.9 },
  { shopifyType: 'cap', ebayCategoryId: '52365', ebayCategoryPath: "Clothes, Shoes & Accessories > Men > Men's Accessories > Hats", confidence: 0.85 },
  { shopifyType: 'scarf', ebayCategoryId: '45238', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Scarves & Shawls", confidence: 0.9 },
  { shopifyType: 'gloves', ebayCategoryId: '105559', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Gloves & Mittens", confidence: 0.9 },
  { shopifyType: 'sunglasses', ebayCategoryId: '79720', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Sunglasses & Accessories", confidence: 0.95 },
  { shopifyType: 'eyewear', ebayCategoryId: '79720', ebayCategoryPath: "Clothes, Shoes & Accessories > Women > Women's Accessories > Sunglasses & Accessories", confidence: 0.8 },
  { shopifyType: 'jewelry', ebayCategoryId: '10968', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery', confidence: 0.7 },
  { shopifyType: 'jewellery', ebayCategoryId: '10968', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery', confidence: 0.7 },
  { shopifyType: 'necklace', ebayCategoryId: '164329', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery > Fine Necklaces & Pendants', confidence: 0.95 },
  { shopifyType: 'earrings', ebayCategoryId: '50647', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery > Fine Earrings', confidence: 0.95 },
  { shopifyType: 'ring', ebayCategoryId: '67681', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery > Fine Rings', confidence: 0.95 },
  { shopifyType: 'bracelet', ebayCategoryId: '50637', ebayCategoryPath: 'Jewellery & Watches > Fine Jewellery > Fine Bracelets', confidence: 0.95 },
  { shopifyType: 'charm', ebayCategoryId: '67681', ebayCategoryPath: 'Jewellery & Watches > Fashion Jewellery > Charms & Charm Bracelets', confidence: 0.85 },
  { shopifyType: 'watch', ebayCategoryId: '31387', ebayCategoryPath: 'Jewellery & Watches > Watches', confidence: 0.9 },
  { shopifyType: 'wristwatch', ebayCategoryId: '31387', ebayCategoryPath: 'Jewellery & Watches > Watches', confidence: 0.9 },
  { shopifyType: 'smartwatch', ebayCategoryId: '178893', ebayCategoryPath: 'Mobile Phones & Communication > Smart Watches', confidence: 0.95 },

  // ── Electronics ──
  { shopifyType: 'phone', shopifyTitleKeywords: ['iphone', 'samsung', 'smartphone'], ebayCategoryId: '9355', ebayCategoryPath: 'Mobile Phones & Communication > Mobile & Smart Phones', confidence: 0.92 },
  { shopifyType: 'smartphone', ebayCategoryId: '9355', ebayCategoryPath: 'Mobile Phones & Communication > Mobile & Smart Phones', confidence: 0.95 },
  { shopifyType: 'mobile phone', ebayCategoryId: '9355', ebayCategoryPath: 'Mobile Phones & Communication > Mobile & Smart Phones', confidence: 0.95 },
  { shopifyType: 'phone case', ebayCategoryId: '20349', ebayCategoryPath: 'Mobile Phones & Communication > Mobile Phone & PDA Accessories > Cases & Covers', confidence: 0.95 },
  { shopifyType: 'phone charger', ebayCategoryId: '123423', ebayCategoryPath: 'Mobile Phones & Communication > Mobile Phone & PDA Accessories > Chargers & Docks', confidence: 0.95 },
  { shopifyType: 'screen protector', ebayCategoryId: '180326', ebayCategoryPath: 'Mobile Phones & Communication > Mobile Phone & PDA Accessories > Screen Protectors', confidence: 0.95 },
  { shopifyType: 'tablet', ebayCategoryId: '171485', ebayCategoryPath: 'Computers/Tablets & Networking > iPads, Tablets & eBook Readers > Tablets & eReaders', confidence: 0.95 },
  { shopifyType: 'ipad', ebayCategoryId: '171485', ebayCategoryPath: 'Computers/Tablets & Networking > iPads, Tablets & eBook Readers > Tablets & eReaders', confidence: 0.97 },
  { shopifyType: 'laptop', ebayCategoryId: '177', ebayCategoryPath: 'Computers/Tablets & Networking > Laptops & Netbooks > PC Laptops & Netbooks', confidence: 0.95 },
  { shopifyType: 'desktop computer', ebayCategoryId: '179', ebayCategoryPath: 'Computers/Tablets & Networking > Desktops & All-in-Ones > PC Desktops & All-in-Ones', confidence: 0.95 },
  { shopifyType: 'keyboard', ebayCategoryId: '33963', ebayCategoryPath: 'Computers/Tablets & Networking > Keyboards, Mice & Pointers > Keyboards & Keypads', confidence: 0.92 },
  { shopifyType: 'mouse', ebayCategoryId: '23160', ebayCategoryPath: 'Computers/Tablets & Networking > Keyboards, Mice & Pointers > Mice, Trackballs & Touchpads', confidence: 0.85 },
  { shopifyType: 'monitor', ebayCategoryId: '80053', ebayCategoryPath: 'Computers/Tablets & Networking > Monitors, Projectors & Accessories > Monitors', confidence: 0.92 },
  { shopifyType: 'printer', ebayCategoryId: '1245', ebayCategoryPath: 'Computers/Tablets & Networking > Printers, Scanners & Supplies > Printers', confidence: 0.95 },
  { shopifyType: 'headphones', ebayCategoryId: '112529', ebayCategoryPath: 'Sound & Vision > Portable Audio & Headphones > Headphones', confidence: 0.95 },
  { shopifyType: 'earbuds', ebayCategoryId: '112529', ebayCategoryPath: 'Sound & Vision > Portable Audio & Headphones > Headphones', confidence: 0.9 },
  { shopifyType: 'speaker', ebayCategoryId: '14990', ebayCategoryPath: 'Sound & Vision > Home Audio & HiFi Separates > Speakers & Subwoofers', confidence: 0.9 },
  { shopifyType: 'bluetooth speaker', ebayCategoryId: '14990', ebayCategoryPath: 'Sound & Vision > Home Audio & HiFi Separates > Speakers & Subwoofers', confidence: 0.92 },
  { shopifyType: 'tv', ebayCategoryId: '11071', ebayCategoryPath: 'Sound & Vision > Televisions', confidence: 0.9 },
  { shopifyType: 'television', ebayCategoryId: '11071', ebayCategoryPath: 'Sound & Vision > Televisions', confidence: 0.95 },
  { shopifyType: 'camera', ebayCategoryId: '31388', ebayCategoryPath: 'Cameras & Photography > Digital Cameras', confidence: 0.88 },
  { shopifyType: 'dslr', ebayCategoryId: '31388', ebayCategoryPath: 'Cameras & Photography > Digital Cameras', confidence: 0.95 },
  { shopifyType: 'lens', ebayCategoryId: '3323', ebayCategoryPath: 'Cameras & Photography > Lenses & Filters > Lenses', confidence: 0.85 },
  { shopifyType: 'tripod', ebayCategoryId: '30078', ebayCategoryPath: 'Cameras & Photography > Tripods, Monopods & Stabilisers', confidence: 0.92 },
  { shopifyType: 'drone', ebayCategoryId: '179697', ebayCategoryPath: 'Cameras & Photography > Drones', confidence: 0.95 },
  { shopifyType: 'gopro', ebayCategoryId: '11724', ebayCategoryPath: 'Cameras & Photography > Camcorders', confidence: 0.9 },
  { shopifyType: 'action camera', ebayCategoryId: '11724', ebayCategoryPath: 'Cameras & Photography > Camcorders', confidence: 0.9 },
  { shopifyType: 'router', ebayCategoryId: '44995', ebayCategoryPath: 'Computers/Tablets & Networking > Home Networking & Connectivity > Wireless Routers', confidence: 0.92 },
  { shopifyType: 'usb cable', ebayCategoryId: '182094', ebayCategoryPath: 'Computers/Tablets & Networking > Cables, Hubs & Adapters > USB Cables, Hubs & Adapters > USB Cables', confidence: 0.92 },
  { shopifyType: 'charger', ebayCategoryId: '123423', ebayCategoryPath: 'Mobile Phones & Communication > Mobile Phone & PDA Accessories > Chargers & Docks', confidence: 0.8 },
  { shopifyType: 'power bank', ebayCategoryId: '20349', ebayCategoryPath: 'Mobile Phones & Communication > Mobile Phone & PDA Accessories > Chargers & Docks > Power Banks', confidence: 0.9 },
  { shopifyType: 'smart home', ebayCategoryId: '177707', ebayCategoryPath: 'Smart Home & Surveillance', confidence: 0.8 },

  // ── Video games ──
  { shopifyType: 'video game', ebayCategoryId: '139973', ebayCategoryPath: 'Video Games & Consoles > Video Games', confidence: 0.92 },
  { shopifyType: 'game', ebayCategoryId: '139973', ebayCategoryPath: 'Video Games & Consoles > Video Games', confidence: 0.5 },
  { shopifyType: 'ps5 game', ebayCategoryId: '139973', ebayCategoryPath: 'Video Games & Consoles > Video Games', confidence: 0.95 },
  { shopifyType: 'xbox game', ebayCategoryId: '139973', ebayCategoryPath: 'Video Games & Consoles > Video Games', confidence: 0.95 },
  { shopifyType: 'console', ebayCategoryId: '139971', ebayCategoryPath: 'Video Games & Consoles > Video Game Consoles', confidence: 0.85 },
  { shopifyType: 'controller', ebayCategoryId: '117042', ebayCategoryPath: 'Video Games & Consoles > Video Game Accessories > Controllers & Attachments', confidence: 0.9 },

  // ── Home / kitchen ──
  { shopifyType: 'mug', ebayCategoryId: '36027', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Tableware, Serving & Linen > Mugs', confidence: 0.95 },
  { shopifyType: 'cup', ebayCategoryId: '36027', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Tableware, Serving & Linen > Mugs', confidence: 0.85 },
  { shopifyType: 'plate', ebayCategoryId: '36027', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Tableware, Serving & Linen > Plates', confidence: 0.85 },
  { shopifyType: 'bowl', ebayCategoryId: '36027', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Tableware, Serving & Linen > Bowls', confidence: 0.85 },
  { shopifyType: 'cutlery', ebayCategoryId: '20637', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Kitchen Tools & Gadgets > Cutlery', confidence: 0.9 },
  { shopifyType: 'knife', ebayCategoryId: '177972', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Kitchen Tools & Gadgets > Knives & Accessories', confidence: 0.88 },
  { shopifyType: 'cookware', ebayCategoryId: '20625', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Cookware', confidence: 0.95 },
  { shopifyType: 'pan', ebayCategoryId: '20625', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Cookware > Frying Pans & Skillets', confidence: 0.85 },
  { shopifyType: 'pot', ebayCategoryId: '20625', ebayCategoryPath: 'Home, Furniture & DIY > Cookware, Dining & Bar > Cookware > Pots & Pans', confidence: 0.8 },
  { shopifyType: 'kettle', ebayCategoryId: '38307', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Kettles', confidence: 0.95 },
  { shopifyType: 'toaster', ebayCategoryId: '20667', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Toasters', confidence: 0.95 },
  { shopifyType: 'blender', ebayCategoryId: '20667', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Blenders', confidence: 0.95 },
  { shopifyType: 'coffee machine', ebayCategoryId: '184772', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Coffee Machines', confidence: 0.95 },
  { shopifyType: 'microwave', ebayCategoryId: '20678', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Microwaves', confidence: 0.95 },
  { shopifyType: 'air fryer', ebayCategoryId: '20667', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Air Fryers', confidence: 0.95 },
  { shopifyType: 'food processor', ebayCategoryId: '20667', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Small Kitchen Appliances > Food Processors', confidence: 0.95 },
  { shopifyType: 'vacuum cleaner', ebayCategoryId: '20614', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Vacuum Cleaners', confidence: 0.95 },
  { shopifyType: 'iron', ebayCategoryId: '71251', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Ironing Boards & Accessories > Irons', confidence: 0.9 },
  { shopifyType: 'fridge', ebayCategoryId: '20713', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Fridges & Freezers', confidence: 0.92 },
  { shopifyType: 'washing machine', ebayCategoryId: '71257', ebayCategoryPath: 'Home, Furniture & DIY > Appliances > Washing Machines & Dryers', confidence: 0.95 },
  { shopifyType: 'heater', ebayCategoryId: '20613', ebayCategoryPath: 'Home, Furniture & DIY > Heating, Cooling & Air > Portable & Space Heaters', confidence: 0.85 },

  // ── Bedding / bath / decor ──
  { shopifyType: 'bedding', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding', confidence: 0.95 },
  { shopifyType: 'duvet', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Duvets', confidence: 0.95 },
  { shopifyType: 'pillow', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Bed Pillows', confidence: 0.92 },
  { shopifyType: 'pillowcase', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Pillow Cases', confidence: 0.95 },
  { shopifyType: 'sheet', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Bed Sheets', confidence: 0.82 },
  { shopifyType: 'blanket', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Blankets & Throws', confidence: 0.92 },
  { shopifyType: 'throw', ebayCategoryId: '20444', ebayCategoryPath: 'Home, Furniture & DIY > Bedding > Blankets & Throws', confidence: 0.85 },
  { shopifyType: 'mattress', ebayCategoryId: '20488', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Beds & Mattresses > Mattresses', confidence: 0.95 },
  { shopifyType: 'towel', ebayCategoryId: '26677', ebayCategoryPath: 'Home, Furniture & DIY > Bath > Towels & Washcloths', confidence: 0.9 },
  { shopifyType: 'bath mat', ebayCategoryId: '133696', ebayCategoryPath: 'Home, Furniture & DIY > Bath > Bath Mats', confidence: 0.95 },
  { shopifyType: 'shower curtain', ebayCategoryId: '100984', ebayCategoryPath: 'Home, Furniture & DIY > Bath > Shower Curtains', confidence: 0.95 },
  { shopifyType: 'rug', ebayCategoryId: '20571', ebayCategoryPath: 'Home, Furniture & DIY > Rugs & Carpets > Rugs', confidence: 0.92 },
  { shopifyType: 'curtain', ebayCategoryId: '20569', ebayCategoryPath: 'Home, Furniture & DIY > Window Treatments & Hardware > Curtains & Pelmets', confidence: 0.92 },
  { shopifyType: 'cushion', ebayCategoryId: '20470', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Cushions', confidence: 0.95 },
  { shopifyType: 'candle', ebayCategoryId: '3639', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Candles & Tea Lights', confidence: 0.95 },
  { shopifyType: 'vase', ebayCategoryId: '20572', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Vases', confidence: 0.95 },
  { shopifyType: 'wall art', ebayCategoryId: '3636', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Wall Hangings', confidence: 0.85 },
  { shopifyType: 'poster', ebayCategoryId: '360', ebayCategoryPath: 'Art > Art Posters', confidence: 0.9 },
  { shopifyType: 'print', ebayCategoryId: '360', ebayCategoryPath: 'Art > Art Prints', confidence: 0.6 },
  { shopifyType: 'painting', ebayCategoryId: '550', ebayCategoryPath: 'Art > Art Paintings', confidence: 0.85 },
  { shopifyType: 'picture frame', ebayCategoryId: '79654', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Photo & Picture Frames', confidence: 0.95 },
  { shopifyType: 'clock', ebayCategoryId: '20561', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Clocks', confidence: 0.9 },
  { shopifyType: 'mirror', ebayCategoryId: '20564', ebayCategoryPath: 'Home, Furniture & DIY > Home Decor > Mirrors', confidence: 0.9 },
  { shopifyType: 'lamp', ebayCategoryId: '112581', ebayCategoryPath: 'Home, Furniture & DIY > Lamps, Lighting & Ceiling Fans > Lamps', confidence: 0.88 },
  { shopifyType: 'lighting', ebayCategoryId: '3197', ebayCategoryPath: 'Home, Furniture & DIY > Lamps, Lighting & Ceiling Fans', confidence: 0.78 },
  { shopifyType: 'light bulb', ebayCategoryId: '20706', ebayCategoryPath: 'Home, Furniture & DIY > Lamps, Lighting & Ceiling Fans > Light Bulbs', confidence: 0.95 },
  { shopifyType: 'fairy lights', ebayCategoryId: '116362', ebayCategoryPath: 'Home, Furniture & DIY > Lamps, Lighting & Ceiling Fans > String Lights', confidence: 0.95 },
  { shopifyType: 'ceiling light', ebayCategoryId: '94487', ebayCategoryPath: 'Home, Furniture & DIY > Lamps, Lighting & Ceiling Fans > Chandeliers & Ceiling Fixtures', confidence: 0.9 },

  // ── Furniture ──
  { shopifyType: 'furniture', ebayCategoryId: '3197', ebayCategoryPath: 'Home, Furniture & DIY > Furniture', confidence: 0.7 },
  { shopifyType: 'sofa', ebayCategoryId: '20508', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Sofas, Armchairs & Suites > Sofas', confidence: 0.95 },
  { shopifyType: 'armchair', ebayCategoryId: '20508', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Sofas, Armchairs & Suites > Armchairs', confidence: 0.95 },
  { shopifyType: 'chair', ebayCategoryId: '20505', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Chairs', confidence: 0.8 },
  { shopifyType: 'table', ebayCategoryId: '20521', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Tables', confidence: 0.78 },
  { shopifyType: 'coffee table', ebayCategoryId: '20481', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Tables > Coffee Tables', confidence: 0.95 },
  { shopifyType: 'dining table', ebayCategoryId: '20481', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Tables > Dining Tables', confidence: 0.95 },
  { shopifyType: 'desk', ebayCategoryId: '88057', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Desks & Computer Furniture > Desks', confidence: 0.9 },
  { shopifyType: 'bed', ebayCategoryId: '20487', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Beds & Mattresses > Beds with Mattresses', confidence: 0.85 },
  { shopifyType: 'bed frame', ebayCategoryId: '115955', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Beds & Mattresses > Bed Frames & Divan Bases', confidence: 0.95 },
  { shopifyType: 'wardrobe', ebayCategoryId: '20487', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Wardrobes & Armoires', confidence: 0.95 },
  { shopifyType: 'bookcase', ebayCategoryId: '20487', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Bookcases, Shelves & Storage', confidence: 0.92 },
  { shopifyType: 'cabinet', ebayCategoryId: '20487', ebayCategoryPath: 'Home, Furniture & DIY > Furniture > Cabinets & Cupboards', confidence: 0.85 },
  { shopifyType: 'storage', ebayCategoryId: '20487', ebayCategoryPath: 'Home, Furniture & DIY > Storage Solutions', confidence: 0.65 },

  // ── Garden ──
  { shopifyType: 'garden', ebayCategoryId: '11700', ebayCategoryPath: 'Garden & Patio', confidence: 0.6 },
  { shopifyType: 'planter', ebayCategoryId: '20518', ebayCategoryPath: 'Garden & Patio > Garden Pots, Troughs & Planters', confidence: 0.92 },
  { shopifyType: 'plant', ebayCategoryId: '181003', ebayCategoryPath: 'Garden & Patio > Plants, Seeds & Bulbs > Plants & Seedlings', confidence: 0.78 },
  { shopifyType: 'seeds', ebayCategoryId: '181003', ebayCategoryPath: 'Garden & Patio > Plants, Seeds & Bulbs > Seeds', confidence: 0.95 },
  { shopifyType: 'garden tool', ebayCategoryId: '29518', ebayCategoryPath: 'Garden & Patio > Garden Hand Tools', confidence: 0.9 },
  { shopifyType: 'bbq', ebayCategoryId: '20619', ebayCategoryPath: 'Garden & Patio > Barbecues, Grills & Smokers', confidence: 0.92 },
  { shopifyType: 'outdoor furniture', ebayCategoryId: '79667', ebayCategoryPath: 'Garden & Patio > Garden & Patio Furniture', confidence: 0.95 },

  // ── DIY / tools ──
  { shopifyType: 'tool', ebayCategoryId: '631', ebayCategoryPath: 'Home, Furniture & DIY > DIY Tools & Workshop Equipment', confidence: 0.55 },
  { shopifyType: 'power tool', ebayCategoryId: '3247', ebayCategoryPath: 'Home, Furniture & DIY > DIY Tools & Workshop Equipment > Power Tools', confidence: 0.95 },
  { shopifyType: 'drill', ebayCategoryId: '3247', ebayCategoryPath: 'Home, Furniture & DIY > DIY Tools & Workshop Equipment > Power Tools > Drills', confidence: 0.92 },
  { shopifyType: 'hand tool', ebayCategoryId: '3250', ebayCategoryPath: 'Home, Furniture & DIY > DIY Tools & Workshop Equipment > Hand Tools', confidence: 0.9 },
  { shopifyType: 'paint', ebayCategoryId: '20763', ebayCategoryPath: 'Home, Furniture & DIY > Building Materials & DIY > Paint, Varnish & Wallpaper', confidence: 0.78 },
  { shopifyType: 'wallpaper', ebayCategoryId: '37581', ebayCategoryPath: 'Home, Furniture & DIY > Building Materials & DIY > Paint, Varnish & Wallpaper > Wallpaper', confidence: 0.95 },

  // ── Beauty ──
  { shopifyType: 'makeup', ebayCategoryId: '31786', ebayCategoryPath: 'Health & Beauty > Make-up', confidence: 0.95 },
  { shopifyType: 'lipstick', ebayCategoryId: '11835', ebayCategoryPath: 'Health & Beauty > Make-up > Lips', confidence: 0.95 },
  { shopifyType: 'foundation', ebayCategoryId: '11836', ebayCategoryPath: 'Health & Beauty > Make-up > Face', confidence: 0.85 },
  { shopifyType: 'mascara', ebayCategoryId: '6562', ebayCategoryPath: 'Health & Beauty > Make-up > Eyes', confidence: 0.95 },
  { shopifyType: 'eyeshadow', ebayCategoryId: '6562', ebayCategoryPath: 'Health & Beauty > Make-up > Eyes', confidence: 0.95 },
  { shopifyType: 'nail polish', ebayCategoryId: '11854', ebayCategoryPath: 'Health & Beauty > Nail Care, Manicure & Pedicure > Nail Polish', confidence: 0.95 },
  { shopifyType: 'skincare', ebayCategoryId: '11863', ebayCategoryPath: 'Health & Beauty > Skin Care', confidence: 0.92 },
  { shopifyType: 'moisturiser', ebayCategoryId: '11863', ebayCategoryPath: 'Health & Beauty > Skin Care > Moisturisers', confidence: 0.95 },
  { shopifyType: 'moisturizer', ebayCategoryId: '11863', ebayCategoryPath: 'Health & Beauty > Skin Care > Moisturisers', confidence: 0.95 },
  { shopifyType: 'serum', ebayCategoryId: '11863', ebayCategoryPath: 'Health & Beauty > Skin Care > Anti-Ageing Products', confidence: 0.85 },
  { shopifyType: 'cleanser', ebayCategoryId: '11863', ebayCategoryPath: 'Health & Beauty > Skin Care > Cleansers & Toners', confidence: 0.9 },
  { shopifyType: 'sunscreen', ebayCategoryId: '152933', ebayCategoryPath: 'Health & Beauty > Skin Care > Sun Care & Tanning', confidence: 0.95 },
  { shopifyType: 'perfume', ebayCategoryId: '26395', ebayCategoryPath: 'Health & Beauty > Fragrances > Women', confidence: 0.88 },
  { shopifyType: 'fragrance', ebayCategoryId: '26395', ebayCategoryPath: 'Health & Beauty > Fragrances', confidence: 0.9 },
  { shopifyType: 'aftershave', ebayCategoryId: '29998', ebayCategoryPath: 'Health & Beauty > Fragrances > Men', confidence: 0.95 },
  { shopifyType: 'cologne', ebayCategoryId: '29998', ebayCategoryPath: 'Health & Beauty > Fragrances > Men', confidence: 0.92 },
  { shopifyType: 'hair care', ebayCategoryId: '11854', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling', confidence: 0.9 },
  { shopifyType: 'shampoo', ebayCategoryId: '11854', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling > Shampoos & Conditioners', confidence: 0.95 },
  { shopifyType: 'conditioner', ebayCategoryId: '11854', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling > Shampoos & Conditioners', confidence: 0.9 },
  { shopifyType: 'hair dryer', ebayCategoryId: '260768', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling > Hair Dryers', confidence: 0.95 },
  { shopifyType: 'straightener', ebayCategoryId: '11858', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling > Hair Straighteners', confidence: 0.95 },
  { shopifyType: 'curler', ebayCategoryId: '11858', ebayCategoryPath: 'Health & Beauty > Hair Care & Styling > Hair Curlers & Wands', confidence: 0.9 },
  { shopifyType: 'razor', ebayCategoryId: '31762', ebayCategoryPath: 'Health & Beauty > Shaving & Hair Removal > Razors & Blades', confidence: 0.95 },
  { shopifyType: 'electric toothbrush', ebayCategoryId: '71191', ebayCategoryPath: 'Health & Beauty > Oral Care > Electric Toothbrushes', confidence: 0.95 },

  // ── Health / vitamins ──
  { shopifyType: 'vitamin', ebayCategoryId: '11776', ebayCategoryPath: 'Health & Beauty > Vitamins & Supplements', confidence: 0.92 },
  { shopifyType: 'supplement', ebayCategoryId: '11776', ebayCategoryPath: 'Health & Beauty > Vitamins & Supplements', confidence: 0.9 },
  { shopifyType: 'protein powder', ebayCategoryId: '180010', ebayCategoryPath: 'Health & Beauty > Vitamins & Supplements > Sports Nutrition > Protein Shakes & Bodybuilding', confidence: 0.95 },
  { shopifyType: 'essential oil', ebayCategoryId: '180960', ebayCategoryPath: 'Health & Beauty > Natural & Alternative Remedies > Aromatherapy', confidence: 0.92 },
  { shopifyType: 'massage', ebayCategoryId: '36447', ebayCategoryPath: 'Health & Beauty > Massage', confidence: 0.75 },
  { shopifyType: 'thermometer', ebayCategoryId: '181790', ebayCategoryPath: 'Health & Beauty > Medical & Mobility > Medical Devices', confidence: 0.85 },

  // ── Sports / outdoor ──
  { shopifyType: 'bike', ebayCategoryId: '177831', ebayCategoryPath: 'Sporting Goods > Cycling > Bicycles', confidence: 0.88 },
  { shopifyType: 'bicycle', ebayCategoryId: '177831', ebayCategoryPath: 'Sporting Goods > Cycling > Bicycles', confidence: 0.95 },
  { shopifyType: 'helmet', ebayCategoryId: '56196', ebayCategoryPath: 'Sporting Goods > Cycling > Helmets & Protective Gear > Helmets', confidence: 0.82 },
  { shopifyType: 'yoga mat', ebayCategoryId: '36303', ebayCategoryPath: 'Sporting Goods > Fitness, Running & Yoga > Yoga & Pilates > Mats', confidence: 0.95 },
  { shopifyType: 'dumbbell', ebayCategoryId: '36297', ebayCategoryPath: 'Sporting Goods > Fitness, Running & Yoga > Weights & Dumbbells > Dumbbells', confidence: 0.95 },
  { shopifyType: 'kettlebell', ebayCategoryId: '36297', ebayCategoryPath: 'Sporting Goods > Fitness, Running & Yoga > Weights & Dumbbells > Kettlebells', confidence: 0.95 },
  { shopifyType: 'treadmill', ebayCategoryId: '15273', ebayCategoryPath: 'Sporting Goods > Fitness, Running & Yoga > Cardio Equipment > Treadmills', confidence: 0.95 },
  { shopifyType: 'exercise bike', ebayCategoryId: '58115', ebayCategoryPath: 'Sporting Goods > Fitness, Running & Yoga > Cardio Equipment > Exercise Bikes', confidence: 0.95 },
  { shopifyType: 'football', ebayCategoryId: '20864', ebayCategoryPath: 'Sporting Goods > Football', confidence: 0.8 },
  { shopifyType: 'tennis racket', ebayCategoryId: '20869', ebayCategoryPath: 'Sporting Goods > Racket Sports > Tennis > Rackets', confidence: 0.95 },
  { shopifyType: 'golf club', ebayCategoryId: '1513', ebayCategoryPath: 'Sporting Goods > Golf > Golf Clubs', confidence: 0.9 },
  { shopifyType: 'golf ball', ebayCategoryId: '20831', ebayCategoryPath: 'Sporting Goods > Golf > Golf Balls', confidence: 0.95 },
  { shopifyType: 'camping', ebayCategoryId: '16034', ebayCategoryPath: 'Sporting Goods > Camping & Hiking', confidence: 0.72 },
  { shopifyType: 'tent', ebayCategoryId: '87114', ebayCategoryPath: 'Sporting Goods > Camping & Hiking > Tents & Canopies > Tents', confidence: 0.9 },
  { shopifyType: 'sleeping bag', ebayCategoryId: '87100', ebayCategoryPath: 'Sporting Goods > Camping & Hiking > Sleeping Bags', confidence: 0.95 },
  { shopifyType: 'backpack hiking', ebayCategoryId: '181383', ebayCategoryPath: 'Sporting Goods > Camping & Hiking > Hiking Backpacks', confidence: 0.9 },
  { shopifyType: 'fishing', ebayCategoryId: '1492', ebayCategoryPath: 'Sporting Goods > Fishing', confidence: 0.7 },
  { shopifyType: 'fishing rod', ebayCategoryId: '36147', ebayCategoryPath: 'Sporting Goods > Fishing > Rods', confidence: 0.95 },
  { shopifyType: 'skateboard', ebayCategoryId: '16262', ebayCategoryPath: 'Sporting Goods > Skateboarding & Scooters > Skateboards > Complete Skateboards', confidence: 0.9 },
  { shopifyType: 'surfboard', ebayCategoryId: '71165', ebayCategoryPath: 'Sporting Goods > Water Sports > Surfing & Stand Up Paddle Boarding > Surfboards', confidence: 0.95 },

  // ── Toys / baby / kids ──
  { shopifyType: 'toy', ebayCategoryId: '220', ebayCategoryPath: 'Toys & Games', confidence: 0.55 },
  { shopifyType: 'action figure', ebayCategoryId: '246', ebayCategoryPath: 'Toys & Games > Action Figures', confidence: 0.92 },
  { shopifyType: 'doll', ebayCategoryId: '237', ebayCategoryPath: 'Toys & Games > Dolls & Bears > Dolls', confidence: 0.92 },
  { shopifyType: 'stuffed animal', ebayCategoryId: '233', ebayCategoryPath: 'Toys & Games > Dolls & Bears > Plush Soft Toys', confidence: 0.92 },
  { shopifyType: 'lego', ebayCategoryId: '19006', ebayCategoryPath: 'Toys & Games > Construction Toys > LEGO', confidence: 0.97 },
  { shopifyType: 'board game', ebayCategoryId: '233', ebayCategoryPath: 'Toys & Games > Games > Board & Traditional Games', confidence: 0.9 },
  { shopifyType: 'puzzle', ebayCategoryId: '11742', ebayCategoryPath: 'Toys & Games > Jigsaw Puzzles', confidence: 0.88 },
  { shopifyType: 'model', ebayCategoryId: '2562', ebayCategoryPath: 'Toys & Games > Model Trains & Railways', confidence: 0.55 },
  { shopifyType: 'toy car', ebayCategoryId: '222', ebayCategoryPath: 'Toys & Games > Diecast & Toy Vehicles > Cars, Trucks & Vans', confidence: 0.92 },
  { shopifyType: 'baby clothes', ebayCategoryId: '3082', ebayCategoryPath: 'Baby > Baby Clothes, Shoes & Accessories', confidence: 0.95 },
  { shopifyType: 'baby bottle', ebayCategoryId: '20400', ebayCategoryPath: 'Baby > Feeding > Bottles', confidence: 0.95 },
  { shopifyType: 'pram', ebayCategoryId: '66700', ebayCategoryPath: 'Baby > Pushchairs, Prams & Accessories > Pushchairs & Prams', confidence: 0.95 },
  { shopifyType: 'stroller', ebayCategoryId: '66700', ebayCategoryPath: 'Baby > Pushchairs, Prams & Accessories > Pushchairs & Prams', confidence: 0.95 },
  { shopifyType: 'car seat', ebayCategoryId: '66692', ebayCategoryPath: 'Baby > Baby & Toddler Car Seats', confidence: 0.92 },
  { shopifyType: 'nappy', ebayCategoryId: '20403', ebayCategoryPath: 'Baby > Nappy Changing', confidence: 0.9 },
  { shopifyType: 'kids clothes', ebayCategoryId: '171146', ebayCategoryPath: 'Clothes, Shoes & Accessories > Kids > Girls', confidence: 0.78 },

  // ── Pet ──
  { shopifyType: 'pet', ebayCategoryId: '1281', ebayCategoryPath: 'Pet Supplies', confidence: 0.6 },
  { shopifyType: 'dog', ebayCategoryId: '20742', ebayCategoryPath: 'Pet Supplies > Dog Supplies', confidence: 0.7 },
  { shopifyType: 'dog food', ebayCategoryId: '63852', ebayCategoryPath: 'Pet Supplies > Dog Supplies > Dog Food', confidence: 0.95 },
  { shopifyType: 'dog toy', ebayCategoryId: '20742', ebayCategoryPath: 'Pet Supplies > Dog Supplies > Dog Toys', confidence: 0.92 },
  { shopifyType: 'dog collar', ebayCategoryId: '20742', ebayCategoryPath: 'Pet Supplies > Dog Supplies > Collars, Leads & Harnesses', confidence: 0.92 },
  { shopifyType: 'dog bed', ebayCategoryId: '20742', ebayCategoryPath: 'Pet Supplies > Dog Supplies > Beds', confidence: 0.9 },
  { shopifyType: 'cat food', ebayCategoryId: '63851', ebayCategoryPath: 'Pet Supplies > Cat Supplies > Cat Food', confidence: 0.95 },
  { shopifyType: 'cat toy', ebayCategoryId: '20741', ebayCategoryPath: 'Pet Supplies > Cat Supplies > Cat Toys', confidence: 0.92 },
  { shopifyType: 'cat litter', ebayCategoryId: '20741', ebayCategoryPath: 'Pet Supplies > Cat Supplies > Litter & Cleaning', confidence: 0.95 },
  { shopifyType: 'fish tank', ebayCategoryId: '20754', ebayCategoryPath: 'Pet Supplies > Fish & Aquariums > Aquariums & Tanks', confidence: 0.92 },
  { shopifyType: 'bird cage', ebayCategoryId: '20754', ebayCategoryPath: 'Pet Supplies > Bird Supplies > Cages', confidence: 0.92 },

  // ── Books / media ──
  { shopifyType: 'book', ebayCategoryId: '267', ebayCategoryPath: 'Books, Comics & Magazines > Books', confidence: 0.8 },
  { shopifyType: 'fiction book', ebayCategoryId: '377', ebayCategoryPath: 'Books, Comics & Magazines > Books > Fiction', confidence: 0.92 },
  { shopifyType: 'textbook', ebayCategoryId: '2228', ebayCategoryPath: 'Books, Comics & Magazines > Textbooks', confidence: 0.95 },
  { shopifyType: 'cookbook', ebayCategoryId: '2228', ebayCategoryPath: 'Books, Comics & Magazines > Books > Cookery', confidence: 0.92 },
  { shopifyType: 'magazine', ebayCategoryId: '280', ebayCategoryPath: 'Books, Comics & Magazines > Magazines', confidence: 0.95 },
  { shopifyType: 'comic', ebayCategoryId: '63', ebayCategoryPath: 'Books, Comics & Magazines > Comics', confidence: 0.9 },
  { shopifyType: 'vinyl', ebayCategoryId: '176985', ebayCategoryPath: 'Music > Records', confidence: 0.95 },
  { shopifyType: 'cd', ebayCategoryId: '11233', ebayCategoryPath: 'Music > CDs', confidence: 0.82 },
  { shopifyType: 'dvd', ebayCategoryId: '617', ebayCategoryPath: 'Films & TV > DVDs & Blu-rays', confidence: 0.9 },
  { shopifyType: 'blu-ray', ebayCategoryId: '617', ebayCategoryPath: 'Films & TV > DVDs & Blu-rays', confidence: 0.92 },

  // ── Automotive ──
  { shopifyType: 'car part', ebayCategoryId: '6030', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Parts & Accessories', confidence: 0.85 },
  { shopifyType: 'car accessory', ebayCategoryId: '6030', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Parts & Accessories', confidence: 0.9 },
  { shopifyType: 'car mat', ebayCategoryId: '36447', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Parts & Accessories > Interior Parts & Accessories > Floor Mats & Carpets', confidence: 0.95 },
  { shopifyType: 'seat cover', ebayCategoryId: '33693', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Parts & Accessories > Interior Parts & Accessories > Seat Covers', confidence: 0.92 },
  { shopifyType: 'dash cam', ebayCategoryId: '170599', ebayCategoryPath: 'Vehicle Parts & Accessories > In-Car Technology, GPS & Security > Dash Cams', confidence: 0.95 },
  { shopifyType: 'motorcycle part', ebayCategoryId: '10063', ebayCategoryPath: 'Vehicle Parts & Accessories > Motorcycle Parts', confidence: 0.92 },
  { shopifyType: 'tyre', ebayCategoryId: '33743', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Wheels, Tyres & Trims > Tyres', confidence: 0.95 },
  { shopifyType: 'tire', ebayCategoryId: '33743', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Wheels, Tyres & Trims > Tyres', confidence: 0.95 },
  { shopifyType: 'car battery', ebayCategoryId: '38635', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Parts & Accessories > Electrical Components > Car Batteries', confidence: 0.95 },
  { shopifyType: 'oil', ebayCategoryId: '36433', ebayCategoryPath: 'Vehicle Parts & Accessories > Car Care & Cleaning > Oils, Fluids & Lubricants', confidence: 0.75 },

  // ── Office / stationery ──
  { shopifyType: 'stationery', ebayCategoryId: '165839', ebayCategoryPath: 'Business, Office & Industrial > Office Supplies & Stationery', confidence: 0.85 },
  { shopifyType: 'pen', ebayCategoryId: '105528', ebayCategoryPath: 'Business, Office & Industrial > Office Supplies & Stationery > Writing Instruments > Pens', confidence: 0.88 },
  { shopifyType: 'pencil', ebayCategoryId: '105528', ebayCategoryPath: 'Business, Office & Industrial > Office Supplies & Stationery > Writing Instruments > Pencils', confidence: 0.88 },
  { shopifyType: 'notebook', ebayCategoryId: '11675', ebayCategoryPath: 'Business, Office & Industrial > Office Supplies & Stationery > Notebooks & Writing Pads', confidence: 0.82 },
  { shopifyType: 'planner', ebayCategoryId: '11675', ebayCategoryPath: 'Business, Office & Industrial > Office Supplies & Stationery > Diaries, Planners & Calendars', confidence: 0.88 },
  { shopifyType: 'sticker', ebayCategoryId: '11675', ebayCategoryPath: 'Crafts > Scrapbooking & Paper Crafts > Stickers', confidence: 0.6 },
  { shopifyType: 'gift card', ebayCategoryId: '172008', ebayCategoryPath: 'Gift Cards & Vouchers', confidence: 0.85 },

  // ── Crafts / art supplies ──
  { shopifyType: 'craft', ebayCategoryId: '14339', ebayCategoryPath: 'Crafts', confidence: 0.55 },
  { shopifyType: 'yarn', ebayCategoryId: '11754', ebayCategoryPath: 'Crafts > Knitting & Crochet > Yarns', confidence: 0.95 },
  { shopifyType: 'fabric', ebayCategoryId: '14339', ebayCategoryPath: 'Crafts > Fabric & Textiles', confidence: 0.85 },
  { shopifyType: 'beads', ebayCategoryId: '83451', ebayCategoryPath: 'Crafts > Beads & Jewellery Making > Beads', confidence: 0.9 },
  { shopifyType: 'art supply', ebayCategoryId: '11804', ebayCategoryPath: 'Crafts > Art Supplies', confidence: 0.85 },

  // ── Musical instruments ──
  { shopifyType: 'guitar', ebayCategoryId: '33034', ebayCategoryPath: 'Musical Instruments > Guitars & Basses', confidence: 0.92 },
  { shopifyType: 'piano', ebayCategoryId: '180012', ebayCategoryPath: 'Musical Instruments > Pianos, Keyboards & Organs', confidence: 0.92 },
  { shopifyType: 'keyboard instrument', ebayCategoryId: '38088', ebayCategoryPath: 'Musical Instruments > Pianos, Keyboards & Organs > Electronic Keyboards', confidence: 0.92 },
  { shopifyType: 'drum', ebayCategoryId: '180014', ebayCategoryPath: 'Musical Instruments > Percussion', confidence: 0.85 },
  { shopifyType: 'violin', ebayCategoryId: '10175', ebayCategoryPath: 'Musical Instruments > String > Orchestral > Violins', confidence: 0.95 },
  { shopifyType: 'ukulele', ebayCategoryId: '16224', ebayCategoryPath: 'Musical Instruments > Guitars & Basses > Ukuleles', confidence: 0.95 },

  // ── Food / pantry (limited — often restricted on eBay) ──
  { shopifyType: 'tea', ebayCategoryId: '38182', ebayCategoryPath: 'Home, Furniture & DIY > Food & Drink > Drinks > Tea', confidence: 0.88 },
  { shopifyType: 'coffee', ebayCategoryId: '38182', ebayCategoryPath: 'Home, Furniture & DIY > Food & Drink > Drinks > Coffee', confidence: 0.85 },
  { shopifyType: 'chocolate', ebayCategoryId: '14308', ebayCategoryPath: 'Home, Furniture & DIY > Food & Drink > Chocolate', confidence: 0.88 },
  { shopifyType: 'snack', ebayCategoryId: '14308', ebayCategoryPath: 'Home, Furniture & DIY > Food & Drink > Snack Food', confidence: 0.75 },

  // ── Collectibles ──
  { shopifyType: 'trading card', ebayCategoryId: '183454', ebayCategoryPath: 'Collectables > Collectable Card Games > CCG Individual Cards', confidence: 0.88 },
  { shopifyType: 'pokemon card', ebayCategoryId: '183454', ebayCategoryPath: 'Collectables > Collectable Card Games > CCG Individual Cards > Pokemon', confidence: 0.95 },
  { shopifyType: 'coin', ebayCategoryId: '11116', ebayCategoryPath: 'Coins & Paper Money > Coins', confidence: 0.8 },
  { shopifyType: 'stamp', ebayCategoryId: '260', ebayCategoryPath: 'Stamps', confidence: 0.82 },
  { shopifyType: 'antique', ebayCategoryId: '20081', ebayCategoryPath: 'Antiques', confidence: 0.65 },
]
